name: "steam"
recbole_config_file: "configs/recbole/steam/implicit_user_prefs.yaml"

cat_feat_field: "genres"

user_feat_cols: ["user_id"]

user_pref_net:
  cols_to_remove: ['app_name', 'developer', 'early_access', 'genres', 'product_id', 'metascore', 'publisher', 'timestamp', 'sentiment', 'specs', 'tags', 'title', "label"]
recommender_net:
  cols_to_remove: [ "timestamp", "label" ]