_target_: recbole.model.context_aware_recommender.xDeepFM

config: {
  LABEL_FIELD: None,
  device: "cuda",
  double_tower: False,
  numerical_features: [],
  embedding_size: 10,
  mlp_hidden_size: [ 128,128,128 ],
  reg_weight: 5e-4,
  dropout_prob: 0.2,
  direct: False,
  cin_layer_size: [ 100,100,100 ],
}
dataset: null
